baseURL = "http://localhost:1313"
languageCode = "en"
title = "Ethon Blog"
theme = "erblog"
paginate = 3


[params]
    author = "Ethon Wu"
    #logo = "//blog.ertuil.top/avater.png"
    bio = """
    <p> 寫寫文章，以備不時之需 </p>
    """
    portrait = "/img/portrait.jpg"


[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
    

# [[menu.main]]
#     identifier = "zone"
#     name = "Zone"
#     url = "/zone/"
#     weight = 10

[[menu.footer]]
    identifier = "home"
    name = "home"
    url = "/"
    weight = 1

[[menu.footer]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2

[taxonomies]
#category = "categories"
tag = "tags"
#series = "series"

[[menu.icon]]
    url = "m10517039@gemail.yuntech.edu.tw"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/Ethonwu"
    name = "github"
    weight = 1

